apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
  - image: adegiuli/kubia-unhealthy:0.2
    name: kubia
    livenessProbe:
      httpGet:
        path: /
        port:  8080
